language: go

go:
  - 1.8
  - 1.9
  - 1.10.x
  - 1.11
  - 1.12
  - 1.13.x

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

